config/routes.rb
Rails.application.routes.draw do

  root to: 'courses#index'

  get '/courses', to: 'courses#index', as: 'courses'
  get '/courses/something_else', to: 'courses#something_else'
  get '/courses/new', to: 'courses#new', as: 'new_course'
  get '/courses/:id', to: 'courses#show', as: 'course'
  post '/courses', to: 'courses#create'
  get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'
  patch '/courses/:id', to: 'courses#update'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  #resources :courses, only: [:index]

  resources :users, only: [:new, :create]

  # The following is defined by resources
  # index
  # get '/students', to: 'students#index', as: 'students'
  # # new
  # get '/students/new', to: 'students#new'
  # #show
  # get '/students/:id', to: 'students#show', as: 'student'
  # #edit
  # get '/students/:id/edit', to: 'students#edit'
  # # create
  # post '/students', to: 'students#create'
  # # update
  # patch '/students/:id', to: 'students#update'
  # # delete
  # delete '/students/:id', to: 'students#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, format: {without: /\Adog\z/i, message: "don't just make it dog!!!!"}

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # validate :password_and_confirmation_match

  # def password=(password)
  #   self.password_digest = salt_and_hash(password)
  # end

  # private
  #
  # def password_and_confirmation_match
  #   if password_comfirmation && password_comfirmation != password
  #     errors.add(:password, 'must match confirmation')
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def authorize_user
    unless logged_in?
      flash[:notice] = "You must be logged in to do that"
      redirect_to login_path and return
    end
  end

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authorize_user, only: [:new, :create, :edit]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:name, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_course_path
    else
      flash[:notice] = "Username or password incorrect"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_course_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/courses/edit.html.erb
<h1>Edit a Course</h1>

<%= form_for(@course) do |f| %>
  <%= f.text_field(:name) %>
  <%= f.submit %>
<% end %>

app/views/courses/index.html.erb
<h1>COURSES!!!</h1>

<% if session['guest_id'] %>
  <p>I know that you have been here before... your id is <%= session['guest_id']%></p>
<% end %>

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to(course.name, course) %> - <%= course.description %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to('Create a Course', new_course_path) %>
<% end %>

app/views/courses/new.html.erb
<h1>Create a Course</h1>

<% if @course.errors.any? %>
  <ul>
    <% @course.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@course) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h1>Show a Course</h1>

<div>
  <h2><%= @course.name %></h2>
  <p><%= @course.description %></p>
</div>

app/views/courses/something_else.html.erb
<h1>BOY - THIS IS SOMETHING ELSE</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if logged_in? %>
        <li>Welcome, <%= current_user.username  %></li>
        <li><%= link_to "Logout", logout_path, method: 'delete'%></li>
      <% else %>
        <li><%= link_to "Log In", login_path%></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>